version: '3'
services:
  app:
    image: dinmo-app:latest
    container_name: dinmo-app
    ports:
      - '8000:8000'
    restart: always
    volumes:
      - ./app:/app
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - '6500:5432'
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db: